---
title: 
author: 
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
# Packages
library(tidyverse)
library(here)
# Parameters
  file_data <- here("data/fractions_combined.rds")

#===============================================================================

# read in data
  df <- read_rds(file_data) 

```

## fPOM amount
```{r echo=FALSE}
df %>% 
  ggplot(aes(x = water_content, y = fPOM_dry_mg_g, fill = sampling_point)) +
  geom_boxplot(outlier.shape = NA) + 
  labs(fill = "sampling_point") + 
  geom_point(position = position_jitterdodge(jitter.width = 0.025), alpha = 0.3, size = 2) +
  theme_bw(base_size = 16) + 
  ylim(0,50) + 
  labs(x = "Water content", y = "fPOM amount (mg/g soil)") +
  facet_wrap(.~litter)
```

fPOM amount seems to decrease from begininng to end of incubation at high water content but remain similar at low water content. Thos fits delta13C-CO2 data that shows higher delta values at higher water content.

### Subsection

## Section 2

